apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: data-project-orders
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: itayb/spark:3.1.1-hadoop-3.2.0-aws
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///data-project/jobs/orders.py
  sparkVersion: 3.1.1
  timeToLiveSeconds: 60
  restartPolicy:
    type: Never
  volumes:
    - name: project
      emptyDir: {}
  driver:
    cores: 1
    memory: 1024m
    serviceAccount: spark-driver
    envFrom:
      - secretRef:
          name: s3-credentials
    volumeMounts:
      - name: project
        mountPath: /data-project
    initContainers:
      - name: git-clone
        image: alpine/git:2.40.1
        command:
          - sh
          - -c
          - git clone --depth=1 https://github.com/VladimirSulikaev/spark-airflow-greenplum-pipeline.git /data-project
        volumeMounts:
          - name: project
            mountPath: /data-project
  executor:
    cores: 1
    instances: 1
    memory: 2048m
    envFrom:
      - secretRef:
          name: s3-credentials

