apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: replace_me
  AWS_SECRET_ACCESS_KEY: replace_me
  S3_ENDPOINT: https://s3.example.com
  S3_REGION: us-east-1
  RAW_DATA_PATH: s3a://raw-data
  REPORTS_PATH: s3a://data-project/reports
